// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// DO NOT EDIT THIS FILE - this calls mobile entry point to keep consistent.
fn main() {
    annex_lib::run()
}
